XBE_TITLE = TES3X\ manager
SRCS = $(CURDIR)/main.c $(CURDIR)/builds.c $(CURDIR)/xbe.c $(CURDIR)/json.c \
       $(CURDIR)/sha256.c $(CURDIR)/zstd/zstddeclib.c
NXDK_DIR ?= $(CURDIR)/../../..
NXDK_SDL = y

include $(NXDK_DIR)/Makefile
