"""Talk to the payload's network driver (the `multiplayer` patch).

    tes3x net listen                     # console broadcasts on UDP 26500
    tes3x net ping 192.0.2.50             # echo round trips to `tes3xnet up`
    tes3x net listen --tunnel 9369       # the same through xemu's udp backend
    tes3x net ping 10.0.2.15 --tunnel 9369
    tes3x net serve --tunnel 9369 --bot   # plus a player circling the first client
    tes3x net serve --tunnel 9369 --bot --bot-say 2 --drop 0.2   # events under loss
    tes3x net serve --tunnel 9369 --bot --bot-owns 20:60   # the bot runs the cell
    tes3x net serve --tunnel 9369 --tunnel 9371   # two xemus, one per tunnel
    tes3x net serve --tunnel 9369 --send FILE   # to TES3X on each console's U:
    tes3x net plugin OUT.esp --master Morrowind.esm   # the ghost plugin

With --tunnel PORT this tool is the guest's only peer: xemu sends each guest Ethernet frame to
PORT as one datagram and accepts frames on PORT+1 (`tes3x xemu --net-tunnel PORT`), so ping
answers ARP itself and resolves the console's MAC before it pings."""

from .proto import (ACTOR, ACTORS, ACTORS_PER_PACKET, ACTOR_DEAD, ACTOR_IN_COMBAT, ACTOR_PERIOD,
                    ADMIN_PASSWORD_MIN, ADMIN_PORT, AGENT_PORT, ANIM_BYTES, ANNOUNCE_WAIT,
                    ARRIVAL_CELL, ATTRIBUTE_NAMES, AUTHORITY_PERIOD, BAN_KINDS, BOT_ID, BROADCAST,
                    BUILD, BULK_ACK, BULK_ACK_BODY, BULK_ACK_EVERY, BULK_BAD_HASH, BULK_CHUNK,
                    BULK_DONE, BULK_FAILED, BULK_MAX, BULK_NAME, BULK_NO_SPACE, BULK_OFFER,
                    BULK_PROBE, BULK_RECEIVING, BULK_REFUSED, BULK_RESEND, BULK_STATUS,
                    BULK_WINDOW_IN, BUSY_SAVING, BYE, CAIUS_PACKAGE, CELL_UNITS,
                    CHARACTERS_LISTED, CHARACTER_BACKUPS, CHARACTER_FILE, CHARACTER_MAGIC,
                    CHARGEN_SOURCE, CHECKPOINT_NAME, CHUNK, CLIENT_RATE, CLOCK, CLOCK_BODY,
                    CLOCK_DEFAULT, CLOCK_INTERVAL, CLOCK_LIMITS, CONTENTS_HEAD, CONTENTS_ROLLED,
                    DEVICE_NAMES, DHCP_CLIENT, DHCP_MAGIC, DHCP_SERVER, DNS_PORT, ENTRY,
                    ENTRY_DATA, EVENT, EVENTS, EVENTS_BYTES, EVENTS_GAP, EVENTS_HEAD,
                    EVENT_ACTOR_EQUIPMENT, EVENT_AFFECT, EVENT_AUTHORITY, EVENT_BOUNTY,
                    EVENT_BUSY, EVENT_CAST, EVENT_CHARS, EVENT_CONTENTS, EVENT_DATA, EVENT_DEATH,
                    EVENT_EQUIPMENT, EVENT_GAME, EVENT_HIT, EVENT_HOLD, EVENT_HOLD_BROKEN,
                    EVENT_IDENTITY, EVENT_LOAD, EVENT_NEWCHAR, EVENT_OBJECTS, EVENT_OFFER,
                    EVENT_OWNERS, EVENT_PICK, EVENT_PLAYER, EVENT_PLAYER_HIT, EVENT_REMOVE,
                    EVENT_RUN, EVENT_SAVE, EVENT_SHOT, EVENT_SNAPSHOT, EVENT_SPAWN, EVENT_SPELL,
                    EVENT_STATUS, EVENT_TEXT, EVENT_WANT, EVENT_WEATHER, EVENT_WELCOME, GAME_LOAD,
                    GAME_NEW, GAME_NONE, GHOSTS, GHOST_CELL, GHOST_PLUGIN, GONE, GUEST_IP,
                    HANDSHAKE1, HANDSHAKE2, HANDSHAKE3, HANDSHAKES_PENDING, HANDSHAKE_KEEP,
                    HANDSHAKE_PAD, HANDSHAKE_RATE, HANDSHAKE_RATE_ALL, HEARTBEAT, HELLO,
                    HELLO_BODY, IDENTITY_FIELDS, IDENTITY_STATS, IDLE_TIMEOUT, INNER, INTERIOR,
                    IN_WORLD, KEEP, KEY, KEY_EXTERIOR, KEY_INTERIOR, LEVEL, LOBBY, LOG_LEVELS,
                    MAGIC, MANAGER, MANAGER_VERSION, MODIFIER, MONTH_DAYS, NOISE_PROTOCOL,
                    NOISE_TAG, NO_ANIM, NO_DISPOSITION, Noise, OBJECT, OBJECTS_PER_EVENT,
                    OBJECT_DELETED, OBJECT_DISABLED, OBJECT_LOCK, OBJECT_LOCKED, OUTER,
                    OWNERS_PER_EVENT, OWNER_HOLD, OWNER_MARGIN, OWNER_PAIR, OWNER_STALE,
                    PACE_PACKETS, PACE_WINDOW, PASSWORD_MAX, PASSWORD_RATE, PEER, PEER_IP,
                    PEER_MAC, PICK_CHARACTER, PICK_NEW, PICK_START, PING, PLACE, PLACE_HOLD,
                    PLACE_NEAR, PLAYER_ALIVE, PLAYER_BOUNTY, PLAYER_DEATH, PLAYER_EFFECTS,
                    PLAYER_EFFECTS_MAX, PLAYER_EFFECT_BYTES, PLAYER_IDENTITY, PLAYER_ITEMS,
                    PLAYER_JOURNAL, PLAYER_LEVEL, PLAYER_MODIFIERS, PLAYER_PLACE, PLAYER_READY,
                    PLAYER_RESPAWN, PLAYER_SKILLS, PLAYER_SPELLS, PLAYER_TOPICS, PLAYER_VITALS, PLAYER_WORN,
                    PONG, PORT, POSITION_LIMIT, PROLOGUE, QUEST_INDICES, REFUSE, REFUSED_BANNED,
                    REFUSED_FULL, REFUSED_KICKED, REFUSED_LOAD_ORDER, REFUSED_PASSWORD,
                    REFUSED_PROTOCOL, REFUSED_STALE, REFUSE_BODY, RELAY, REMOTE_ADMIN_PORT,
                    REMOTE_CHALLENGE, REMOTE_COMMAND, REMOTE_HEAD, REMOTE_HELLO, REMOTE_MAGIC,
                    REMOTE_NONCE, REMOTE_NONCES, REMOTE_NONCE_SECONDS, REMOTE_REFUSED,
                    REMOTE_REPLY, REMOTE_VERSION, RESEND, RESPAWN, RESPAWN_PLACES, SEALED,
                    SERVER_EVENTS, SHOT, SKILL, SKILL_NAMES, SOURCE_SPELL, SPAWN, SPAWN_COUNT,
                    SPAWN_DATA, SPAWN_IDS, SPAWN_LEVELED, SPAWN_REMOVED, SPAWN_SUMMON, SPAWN_TWIN,
                    SPAWN_TWIN_SECONDS, SPELL, SPELLS_ADD, SPELLS_REMOVE, SPELLS_SNAPSHOT,
                    SPYMASTER_DONE, SPYMASTER_GIVEN, SPYMASTER_QUEST, STANCE, STARTS, START_NAME,
                    STATE, STATE_BODY, STATE_SIZE, STATUS, STREAM_NAME, T3MP, T3MP_VERSION,
                    TARGETED, UPLOAD_FILES, VITALS, WEATHERS, WEATHER_ENTRY, WEATHER_OFFER,
                    WEATHER_PER_EVENT, WELCOME, admin_secret, aead_nonce, cell_keys,
                    checkpoint_name, crypto, describe_contents, describe_identity, describe_key,
                    describe_level, describe_object, describe_spawn, describe_state,
                    describe_status, describe_weather, effect_id_not_bound, fingerprint, finite,
                    load_order_hash, now_us, pack_actor_equipment, pack_contents, pack_equipment,
                    pack_events, pack_identity, pack_items, pack_journal, pack_topics, pack_names,
                    pack_objects, pack_player_effects, pack_player_identity, pack_removes,
                    pack_spawn, pack_weather, pack_worn, placeable, plain_name, remote_key,
                    same_place, sane_clock, seal, unpack_actor_equipment, unpack_contents,
                    unpack_equipment, unpack_events, unpack_identity, unpack_items,
                    unpack_journal, unpack_objects, unpack_player_effects, unpack_player_identity,
                    unpack_removes, unpack_spawn, unpack_weather, unpack_worn, unseal, wire_text,
                    x25519_public, zstr)
from .server import (Bot, Bucket, Client, Clock, Incoming, Outgoing, PlayerStream, Reliable,
                     RemoteAdmin, Server, World, assign_authority, assign_owners, ban_value,
                     character_slug, decode, keep_character, kept_characters, latest_character,
                     load_admin_password, load_admitted, load_bans, load_password,
                     load_server_key, load_starts, load_world, new_character_folder, quiet_admin,
                     save_bans, save_player, save_world, serve, spawn_twin, summary)
from .tunnel import (Tunnel, arp_frame, checksum, dhcp_reply, dns_reply, free_udp_ports, resolve,
                     udp_frame, udp_from_frame, udp_socket)
from .cli import (FuzzClient, RemoteAdminError, admin_command, fuzz, fuzz_body, listen, main,
                  ping, remote_admin_request)
from .plugin import (chargen_script, ghost_plugin, record, write_ghost_plugin)

from tes3x.paths import resource
import argparse
import glob
import hashlib
import hmac
import json
import math
import os
import queue
import random
import re
import select
import signal
import socket
import struct
import sys
import tes3x.netbuild as tes3x_netbuild
import threading
import time
import traceback

__all__ = [
    'ACTOR',
    'ACTORS',
    'ACTORS_PER_PACKET',
    'ACTOR_DEAD',
    'ACTOR_IN_COMBAT',
    'ACTOR_PERIOD',
    'ADMIN_PASSWORD_MIN',
    'ADMIN_PORT',
    'AGENT_PORT',
    'ANIM_BYTES',
    'ANNOUNCE_WAIT',
    'ARRIVAL_CELL',
    'ATTRIBUTE_NAMES',
    'AUTHORITY_PERIOD',
    'BAN_KINDS',
    'BOT_ID',
    'BROADCAST',
    'BUILD',
    'BULK_ACK',
    'BULK_ACK_BODY',
    'BULK_ACK_EVERY',
    'BULK_BAD_HASH',
    'BULK_CHUNK',
    'BULK_DONE',
    'BULK_FAILED',
    'BULK_MAX',
    'BULK_NAME',
    'BULK_NO_SPACE',
    'BULK_OFFER',
    'BULK_PROBE',
    'BULK_RECEIVING',
    'BULK_REFUSED',
    'BULK_RESEND',
    'BULK_STATUS',
    'BULK_WINDOW_IN',
    'BUSY_SAVING',
    'BYE',
    'Bot',
    'Bucket',
    'CAIUS_PACKAGE',
    'CELL_UNITS',
    'CHARACTERS_LISTED',
    'CHARACTER_BACKUPS',
    'CHARACTER_FILE',
    'CHARACTER_MAGIC',
    'CHARGEN_SOURCE',
    'CHECKPOINT_NAME',
    'CHUNK',
    'CLIENT_RATE',
    'CLOCK',
    'CLOCK_BODY',
    'CLOCK_DEFAULT',
    'CLOCK_INTERVAL',
    'CLOCK_LIMITS',
    'CONTENTS_HEAD',
    'CONTENTS_ROLLED',
    'Client',
    'Clock',
    'DEVICE_NAMES',
    'DHCP_CLIENT',
    'DHCP_MAGIC',
    'DHCP_SERVER',
    'DNS_PORT',
    'ENTRY',
    'ENTRY_DATA',
    'EVENT',
    'EVENTS',
    'EVENTS_BYTES',
    'EVENTS_GAP',
    'EVENTS_HEAD',
    'EVENT_ACTOR_EQUIPMENT',
    'EVENT_AFFECT',
    'EVENT_AUTHORITY',
    'EVENT_BOUNTY',
    'EVENT_BUSY',
    'EVENT_CAST',
    'EVENT_CHARS',
    'EVENT_CONTENTS',
    'EVENT_DATA',
    'EVENT_DEATH',
    'EVENT_EQUIPMENT',
    'EVENT_GAME',
    'EVENT_HIT',
    'EVENT_HOLD',
    'EVENT_HOLD_BROKEN',
    'EVENT_IDENTITY',
    'EVENT_LOAD',
    'EVENT_NEWCHAR',
    'EVENT_OBJECTS',
    'EVENT_OFFER',
    'EVENT_OWNERS',
    'EVENT_PICK',
    'EVENT_PLAYER',
    'EVENT_PLAYER_HIT',
    'EVENT_REMOVE',
    'EVENT_RUN',
    'EVENT_SAVE',
    'EVENT_SHOT',
    'EVENT_SNAPSHOT',
    'EVENT_SPAWN',
    'EVENT_SPELL',
    'EVENT_STATUS',
    'EVENT_TEXT',
    'EVENT_WANT',
    'EVENT_WEATHER',
    'EVENT_WELCOME',
    'FuzzClient',
    'GAME_LOAD',
    'GAME_NEW',
    'GAME_NONE',
    'GHOSTS',
    'GHOST_CELL',
    'GHOST_PLUGIN',
    'GONE',
    'GUEST_IP',
    'HANDSHAKE1',
    'HANDSHAKE2',
    'HANDSHAKE3',
    'HANDSHAKES_PENDING',
    'HANDSHAKE_KEEP',
    'HANDSHAKE_PAD',
    'HANDSHAKE_RATE',
    'HANDSHAKE_RATE_ALL',
    'HEARTBEAT',
    'HELLO',
    'HELLO_BODY',
    'IDENTITY_FIELDS',
    'IDENTITY_STATS',
    'IDLE_TIMEOUT',
    'INNER',
    'INTERIOR',
    'IN_WORLD',
    'Incoming',
    'KEEP',
    'KEY',
    'KEY_EXTERIOR',
    'KEY_INTERIOR',
    'LEVEL',
    'LOBBY',
    'LOG_LEVELS',
    'MAGIC',
    'MANAGER',
    'MANAGER_VERSION',
    'MODIFIER',
    'MONTH_DAYS',
    'NOISE_PROTOCOL',
    'NOISE_TAG',
    'NO_ANIM',
    'NO_DISPOSITION',
    'Noise',
    'OBJECT',
    'OBJECTS_PER_EVENT',
    'OBJECT_DELETED',
    'OBJECT_DISABLED',
    'OBJECT_LOCK',
    'OBJECT_LOCKED',
    'OUTER',
    'OWNERS_PER_EVENT',
    'OWNER_HOLD',
    'OWNER_MARGIN',
    'OWNER_PAIR',
    'OWNER_STALE',
    'Outgoing',
    'PACE_PACKETS',
    'PACE_WINDOW',
    'PASSWORD_MAX',
    'PASSWORD_RATE',
    'PEER',
    'PEER_IP',
    'PEER_MAC',
    'PICK_CHARACTER',
    'PICK_NEW',
    'PICK_START',
    'PING',
    'PLACE',
    'PLACE_HOLD',
    'PLACE_NEAR',
    'PLAYER_ALIVE',
    'PLAYER_BOUNTY',
    'PLAYER_DEATH',
    'PLAYER_EFFECTS',
    'PLAYER_EFFECTS_MAX',
    'PLAYER_EFFECT_BYTES',
    'PLAYER_IDENTITY',
    'PLAYER_ITEMS',
    'PLAYER_JOURNAL',
    'PLAYER_LEVEL',
    'PLAYER_MODIFIERS',
    'PLAYER_PLACE',
    'PLAYER_READY',
    'PLAYER_RESPAWN',
    'PLAYER_SKILLS',
    'PLAYER_SPELLS',
    'PLAYER_TOPICS',
    'PLAYER_VITALS',
    'PLAYER_WORN',
    'PONG',
    'PORT',
    'POSITION_LIMIT',
    'PROLOGUE',
    'PlayerStream',
    'QUEST_INDICES',
    'REFUSE',
    'REFUSED_BANNED',
    'REFUSED_FULL',
    'REFUSED_KICKED',
    'REFUSED_LOAD_ORDER',
    'REFUSED_PASSWORD',
    'REFUSED_PROTOCOL',
    'REFUSED_STALE',
    'REFUSE_BODY',
    'RELAY',
    'REMOTE_ADMIN_PORT',
    'REMOTE_CHALLENGE',
    'REMOTE_COMMAND',
    'REMOTE_HEAD',
    'REMOTE_HELLO',
    'REMOTE_MAGIC',
    'REMOTE_NONCE',
    'REMOTE_NONCES',
    'REMOTE_NONCE_SECONDS',
    'REMOTE_REFUSED',
    'REMOTE_REPLY',
    'REMOTE_VERSION',
    'RESEND',
    'RESPAWN',
    'RESPAWN_PLACES',
    'Reliable',
    'RemoteAdmin',
    'RemoteAdminError',
    'SEALED',
    'SERVER_EVENTS',
    'SHOT',
    'SKILL',
    'SKILL_NAMES',
    'SOURCE_SPELL',
    'SPAWN',
    'SPAWN_COUNT',
    'SPAWN_DATA',
    'SPAWN_IDS',
    'SPAWN_LEVELED',
    'SPAWN_REMOVED',
    'SPAWN_SUMMON',
    'SPAWN_TWIN',
    'SPAWN_TWIN_SECONDS',
    'SPELL',
    'SPELLS_ADD',
    'SPELLS_REMOVE',
    'SPELLS_SNAPSHOT',
    'SPYMASTER_DONE',
    'SPYMASTER_GIVEN',
    'SPYMASTER_QUEST',
    'STANCE',
    'STARTS',
    'START_NAME',
    'STATE',
    'STATE_BODY',
    'STATE_SIZE',
    'STATUS',
    'STREAM_NAME',
    'Server',
    'T3MP',
    'T3MP_VERSION',
    'TARGETED',
    'Tunnel',
    'UPLOAD_FILES',
    'VITALS',
    'WEATHERS',
    'WEATHER_ENTRY',
    'WEATHER_OFFER',
    'WEATHER_PER_EVENT',
    'WELCOME',
    'World',
    'admin_command',
    'admin_secret',
    'aead_nonce',
    'argparse',
    'arp_frame',
    'assign_authority',
    'assign_owners',
    'ban_value',
    'cell_keys',
    'character_slug',
    'chargen_script',
    'checkpoint_name',
    'checksum',
    'crypto',
    'decode',
    'describe_contents',
    'describe_identity',
    'describe_key',
    'describe_level',
    'describe_object',
    'describe_spawn',
    'describe_state',
    'describe_status',
    'describe_weather',
    'dhcp_reply',
    'dns_reply',
    'effect_id_not_bound',
    'fingerprint',
    'finite',
    'free_udp_ports',
    'fuzz',
    'fuzz_body',
    'ghost_plugin',
    'glob',
    'hashlib',
    'hmac',
    'json',
    'keep_character',
    'kept_characters',
    'latest_character',
    'listen',
    'load_admin_password',
    'load_admitted',
    'load_bans',
    'load_order_hash',
    'load_password',
    'load_server_key',
    'load_starts',
    'load_world',
    'main',
    'math',
    'new_character_folder',
    'now_us',
    'os',
    'pack_actor_equipment',
    'pack_contents',
    'pack_equipment',
    'pack_events',
    'pack_identity',
    'pack_items',
    'pack_journal',
    'pack_topics',
    'pack_names',
    'pack_objects',
    'pack_player_effects',
    'pack_player_identity',
    'pack_removes',
    'pack_spawn',
    'pack_weather',
    'pack_worn',
    'ping',
    'placeable',
    'plain_name',
    'queue',
    'quiet_admin',
    'random',
    're',
    'record',
    'remote_admin_request',
    'remote_key',
    'resolve',
    'resource',
    'same_place',
    'sane_clock',
    'save_bans',
    'save_player',
    'save_world',
    'seal',
    'select',
    'serve',
    'signal',
    'socket',
    'spawn_twin',
    'struct',
    'summary',
    'sys',
    'tes3x_netbuild',
    'threading',
    'time',
    'traceback',
    'udp_frame',
    'udp_from_frame',
    'udp_socket',
    'unpack_actor_equipment',
    'unpack_contents',
    'unpack_equipment',
    'unpack_events',
    'unpack_identity',
    'unpack_items',
    'unpack_journal',
    'unpack_objects',
    'unpack_player_effects',
    'unpack_player_identity',
    'unpack_removes',
    'unpack_spawn',
    'unpack_weather',
    'unpack_worn',
    'unseal',
    'wire_text',
    'write_ghost_plugin',
    'x25519_public',
    'zstr',
]
