#!/usr/bin/env python3
"""Bake the console manager's fonts into C: 8-bit coverage atlases and glyph metrics.

The fonts are downloaded once at a pinned SHA-256 into the per-user cache, rasterised with
Pillow's FreeType and written to manager/fontdata.c, with their licences in manager/fonts/.
The output is committed, so building the manager needs neither the fonts nor Pillow.

    tes3x font [--check]
"""

import argparse
import hashlib
import sys
import urllib.request

from tes3x.paths import checkout, data_dir

ROOT = checkout()
OUT = ROOT / "manager" / "fontdata.c"
LICENCES = ROOT / "manager" / "fonts"
BASE = "https://raw.githubusercontent.com/google/fonts/7085eb89a950e85db5b166b7a58d414544b4140c/"
# file: (path under BASE, SHA-256)
FILES = {
    "AlegreyaSans-Regular.ttf": ("ofl/alegreyasans/AlegreyaSans-Regular.ttf",
                                 "8fab634196007afca839f1e5a6fb300976daff55d8528b590ef032f01b14ea10"),
    "AlegreyaSans-Bold.ttf": ("ofl/alegreyasans/AlegreyaSans-Bold.ttf",
                              "a3055a1893759bdbd7504bb22abc583769e7974c49353176eac0b03792c9fb8e"),
    "Cinzel.ttf": ("ofl/cinzel/Cinzel%5Bwght%5D.ttf",
                   "f4d83d34d1f6c741193e4acf4b3dff9531e5a67b6aa65228d00a7db72a4e0f34"),
    "OFL-AlegreyaSans.txt": ("ofl/alegreyasans/OFL.txt",
                             "0677891e6a143f297350d260ad766ad33bfc18ed5fa4f213acf648d6b597ec1a"),
    "OFL-Cinzel.txt": ("ofl/cinzel/OFL.txt",
                       "f2b3029aba64c378bf0963b62945eee15e564fe4330b934c8f2eb058282b5e83"),
}
# fonts the repository already carries
LOCAL = {
    "Fondamento-Regular.ttf": ROOT / "assets" / "fonts" / "Fondamento-Regular.ttf",
    "OFL-Fondamento.txt": ROOT / "assets" / "fonts" / "OFL-Fondamento.txt",
}
# C name: (file, pixel size, weight axis or None, last character, only these characters)
FONTS = {
    "font_body": ("AlegreyaSans-Regular.ttf", 21, None, 255, None),
    "font_bold": ("AlegreyaSans-Bold.ttf", 21, None, 255, None),
    "font_small": ("AlegreyaSans-Regular.ttf", 17, None, 255, None),
    "font_title": ("Cinzel.ttf", 22, 700, 126, None),
    "font_logo": ("Fondamento-Regular.ttf", 34, None, 126, "TES3X"),
}
FIRST = 32
ATLAS_WIDTH = 512


def fetch(name):
    if name in LOCAL:
        return LOCAL[name]
    path, expected = FILES[name]
    cache = data_dir() / "fonts"
    target = cache / name
    if target.is_file():
        return target
    cache.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(BASE + path, timeout=60) as response:
        data = response.read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != expected:
        raise SystemExit(f"{name}: SHA-256 {digest}, expected {expected}")
    target.write_bytes(data)
    return target


def bake(name, file, size, weight, last, only):
    from PIL import Image, ImageDraw, ImageFont

    font = ImageFont.truetype(str(fetch(file)), size)
    if weight is not None:
        font.set_variation_by_axes([weight])
    ascent, descent = font.getmetrics()
    glyphs, bitmaps = [], []
    for code in range(FIRST, last + 1):
        try:
            ch = bytes([code]).decode("cp1252")
        except UnicodeDecodeError:
            ch = None
        if ch is None or (code > 126 and code < 160) or (only and ch not in only + " "):
            glyphs.append((0, 0, 0, 0, 0, 0))
            bitmaps.append(None)
            continue
        advance = round(font.getlength(ch))
        box = font.getbbox(ch, anchor="ls")
        w, h = box[2] - box[0], box[3] - box[1]
        if w <= 0 or h <= 0:
            glyphs.append((0, 0, advance, box[0], 0, 0))
            bitmaps.append(None)
            continue
        image = Image.new("L", (w, h))
        ImageDraw.Draw(image).text((-box[0], -box[1]), ch, font=font, fill=255, anchor="ls")
        glyphs.append((w, h, advance, box[0], box[1], 0))
        bitmaps.append(image)
    # shelf packing, one pixel apart
    x = y = shelf = 0
    placed = []
    for image in bitmaps:
        if image is None:
            placed.append((0, 0))
            continue
        if x + image.width > ATLAS_WIDTH:
            x, y, shelf = 0, y + shelf + 1, 0
        placed.append((x, y))
        x += image.width + 1
        shelf = max(shelf, image.height)
    height = y + shelf
    atlas = Image.new("L", (ATLAS_WIDTH, max(height, 1)))
    for image, at in zip(bitmaps, placed):
        if image is not None:
            atlas.paste(image, at)
    return dict(name=name, ascent=ascent, line=ascent + descent, last=last,
                atlas=atlas, glyphs=glyphs, placed=placed)


def render(fonts):
    out = ["/* Generated by tes3x font; do not edit. Fonts under the SIL Open Font",
           " * License 1.1: Alegreya Sans (c) The Alegreya Sans Project Authors, Cinzel (c) The",
           " * Cinzel Project Authors, Fondamento (c) Astigmatic; the licences are in fonts/. */",
           "",
           '#include "gfx.h"', ""]
    for f in fonts:
        n, atlas = f["name"], f["atlas"]
        data = atlas.tobytes()
        out.append(f"static const unsigned char {n}_alpha[{len(data)}] = {{")
        for i in range(0, len(data), 24):
            out.append("    " + ",".join(str(b) for b in data[i:i + 24]) + ",")
        out.append("};")
        out.append(f"static const struct glyph {n}_glyphs[{len(f['glyphs'])}] = {{")
        for (w, h, adv, ox, oy, _), (x, y) in zip(f["glyphs"], f["placed"]):
            out.append(f"    {{{x}, {y}, {w}, {h}, {ox}, {oy}, {adv}}},")
        out.append("};")
        out.append(f"const struct font {n} = {{{n}_alpha, {atlas.width}, {FIRST}, "
                   f"{len(f['glyphs'])}, {f['ascent']}, {f['line']}, {n}_glyphs}};")
        out.append("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the output is stale")
    args = parser.parse_args()
    text = render([bake(name, *spec) for name, spec in FONTS.items()])
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding="ascii") != text:
            sys.exit(f"{OUT} is stale: run tes3x font")
        return
    OUT.write_text(text, encoding="ascii", newline="\n")
    LICENCES.mkdir(exist_ok=True)
    for name in [*FILES, *LOCAL]:
        if name.endswith(".txt"):
            (LICENCES / name).write_bytes(fetch(name).read_bytes())
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
